blueprint:
  name: Motion-activated Scene
  description: Turn on a sene when motion is detected.
  domain: automation
  source_url: https://github.com/rdonelson/homeassistant/blob/main/components/automation/blueprints/motion_scene.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    override_entity:
      name: Motion Override
      selector:
        entity:
          domain: input_boolean
    illuminance_entity:
      name: Illuminance Sensor
      selector:
        entity:
          domain: sensor
    illuminance_below:
      name: Illuminance Below
      description: Scene will be triggered below this brightness
      default: 100
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: lux
    scene_on:
      name: Scene to Turn On
      selector:
        target:
          entity:
            domain: scene
    scene_off:
      name: Scene to Turn Off
      selector:
        target:
          entity:
            domain: scene
    no_motion_wait:
      name: Wait time
      description: Time to leave the scene on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  - condition: state
    entity_id: !input override_entity
    state: "off"
  - condition: numeric_state
    entity_id: !input illuminance_entity
    below: !input illuminance_below

action:
  - alias: "Turn on the scene"
    service: scene.turn_on
    target: !input scene_on
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - if:
      - condition: state
        entity_id: !input override_entity
        state: "off"
    then:
      - service: scene.turn_on
        target: !input scene_off